### ISSUE TITLE
ESM

### ISSUE THREAD

**Issue by tactusoft** [chunkangwong/arcgis-national-parks-visitorship#1]
Good job, how hard is it to use ESM and not loader? Thanks

**Comment by chunkangwong** [comment]
Good question. I have never considered using ESM because I did not realized the existence of @arcgis/core NPM package. I will certainly look into it to see if it is feasible to implement @arcgis/core into this React app. Thanks for the information.

**Comment by tactusoft** [comment]
Thank you. I will try to implement it as well. Is it possible for the calcite interface to be in a separate component so that the App.js is just calling it?

**Comment by chunkangwong** [comment]
I tried the ESM and it definitely feels more natural then using loader. Unfortunately the ESM module does not work with the Map component from react-arcgis module. If I were to choose I would definitely go with the ESM and I am going to refactor based on it. The Map component from react-arcgis module definitely feels nice at first but the flaw of having to work with the loadModule loader outweighs the benefit.

**Comment by tactusoft** [comment]
Good morning. I have already done it, I just need to add the home and the featurelayer. If you want I can send it to you?

**Comment by chunkangwong** [comment]
I have refactored the whole project to using ESM. I ran into some problems implementing the ESM FeatureLayer with the react-arcgis Map module. I thought there were some hidden incompatibilities so I refactored everything. Thanks for your recommendation of using ESM. It feels more natural to me than using moduleLoader.
